import type { Metadata } from "next";
import { Hind_Siliguri, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

import Header from "@/components/site/Header";
import Footer from "@/components/site/Footer";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const garamond = Cormorant_Garamond({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          (hindSiliguri.className,
          garamond.className,
          "max-w-screen-xl mx-1 md:mx-auto")
        }
      >
        <Header></Header>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
